language: go

go:
  - "1.10.x"

before_install:                                                                 
  - docker build -t patricelee/daydaymovie:last -f ./deploy/Dockerfile .
  - docker build -t patricelee/howing-crawler:last -f ./deploy/Dockerfile.crawler .

install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push patricelee/daydaymovie:last
  - docker push patricelee/howing-crawler:last