language: go

go:
  - "1.10.x"

before_install:                                                                 
  - docker build -t patricelee/daydaymovie -f ./deploy/Dockerfile .


script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push patricelee/daydaymovie